import React from 'react'
import Head from 'next/head'
import HomePage from '../components/pages/Home'
import { firebaseDb } from 'utils/firebase'
import { collection, getDocs, getFirestore, query, limit } from "firebase/firestore";

function Home({ sets }) {

  const loadMore = () => {
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage sets={sets} />

      <button onClick={() => loadMore()}>Load More</button>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const orderedDocs = query(collection(firebaseDb, "sets"), limit(100))
  const querySnapshot = await getDocs(orderedDocs);
  const sets = querySnapshot.docs.map(doc => doc.data())

  return { props: { sets: sets || null  } }
}

export default Home;
