import React from 'react'
import Head from 'next/head'
import HomePage from '../components/pages/Home'
import axios from 'axios';

function Home({ companies }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage companies={companies} />
    </>
  )
}

export default Home;

export const getServerSideProps = async (ctx) => {
  var options = {
    method: 'GET',
    url: 'https://yahoofinance-stocks1.p.rapidapi.com/companies/list-by-exchange',
    params: {ExchangeCode: 'NMS'},
    headers: {
      'x-rapidapi-host': 'yahoofinance-stocks1.p.rapidapi.com',
      'x-rapidapi-key': 'f0e8153803msh7efbc70383f5751p1baaecjsn6c32aa1b3e5a'
    }
  };
  
  const companies = await axios.request(options).then(function (response) {
    return response.data
  }).catch(function (error) {
    console.error(error);
  });

  return { props: { companies: companies || null  } }
}